version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: DB_LATERRAZA
      MYSQL_ROOT_PASSWORD: 123

    ports:
      - 3307:3306

    volumes:
      - ./db:/var/lib/mysql